### ISSUE TITLE
Entrega 2.2: Execução

### ISSUE THREAD

**Issue by caburu** [lucasdanielian/TrabalhoUm#112]
* '- Mensagem de imagem não carregada (diretório colocado direto no código diferente do que realmente existe). 
* '+ Habilitação dos botões de itens ok quando usando botões de direção e de pegar itens.
  * '- Mas ao colegar itens via comando de texto, botão do item não foi habilitado na mochila (e consegui pegar o mesmo item duas vezes, ao usar depois o botão).
* '- Caixa de comando às vezes fica diminuída, impossibilitando o uso.
* '+ Itens do feeback de execução anterior corrigidos (exceto navegação).

**Comment by vssjunior** [comment]
Boa tarde Júlio, corrigimos os itens elencados acima porem você poderia esplicar melhor o exceto navegação?

**Comment by caburu** [comment]
No feedback de execução anterior #79 eu tinha colocado o texto abaixo. Mas creio que para vocês mudarem agora vai mexer muito na lógica do jogo. Então é melhor deixar como está.
* A questão de poder tentar acessar qualquer ambiente a partir do local atual (ou pelo menos tentar) fere um pouco a ideia de um jogo adventure baseado em movimentação.

**Comment by vssjunior** [comment]
Muito obrigado pelo esclarecimento Júlio.
OBS: O tempo não nos permitiu resolver esta questão para segunda entrega, mas para a última nós já  corrigimos, agora os ambientes não tem saída de todos para todos mais.
