### ISSUE TITLE
Entrega 2.2: História 6

### ISSUE THREAD

**Issue by caburu** [lucasdanielian/TrabalhoUm#114]
Não identifiquei pontuação no jogo.
* Se a ideia foi usar os dias restantes é pouco. 
* Poderia ter pontos ao pegar itens, coisas que perdesse pontos, etc.

**Comment by vssjunior** [comment]
Boa noite júlio, continuaremos com a idéia dos dias como pontuação, pois toda emoção do jogo e cara conseguir salvar o irmão dele em menos dias, porém antes cada movimento entre ambientes significava 3 dias a menos, agora esses dias aumentam e retraem de acordo com alguns ambientes passados e alguns itens coletados. Acreditamos que seria essa emoção que você queria!
