### ISSUE TITLE
Entrega 2.2: Diagrama de Classes UML

### ISSUE THREAD

**Issue by caburu** [lucasdanielian/TrabalhoUm#115]
- Diagrama possui classes desatualizadas (ex: Jogo x RegraDeNegocio), classes com 'Atribute1' e coisas do tipo; faltam relacionamentos entre classes (ex: subclasses de Ambiente), etc.

**Comment by vssjunior** [comment]
Ok professor, estamos tentando fazer o melhor possível, mas como está muito grande o diagrama está dificultando sua confecção, pois são muitas ligações as vezes estamos nos perdendo nas ligações uma vez que são muitas setas representando muitos relacionamentos.
