### ISSUE TITLE
Entrega 2.2: Javadoc

### ISSUE THREAD

**Issue by caburu** [lucasdanielian/TrabalhoUm#116]
Javadoc não veio nessa entrega.

**Comment by vssjunior** [comment]
Julio acreditavamos que o problema tinha sido resolvido (até você mesmo que nos ajudou a resolver este problema nos auxiliando com o gitignore) mas como não resolveu pesquisamos e encontramos alguns problemas com cached, limpamos os mesmos e parece ter solucionado o problema (git rm --cached build/)
