### ISSUE TITLE
Entrega 2.2: Replicações de Código

### ISSUE THREAD

**Issue by caburu** [lucasdanielian/TrabalhoUm#117]
Replicações de código na classe TelaJogo:
* Trechos repetidos nos eventos de botões.
* Há três métodos para adicionar componentes a painel (poderia ser apenas um que recebesse o painel a ser usado por parâmetro).
* Grande repetição no método 'prepararItensAmbientes'
  * chamadas 'setIcon' poderiam ser feitas apenas na inicialização da tela;
  * e chamadas 'setEnabled' poderiam ser feitas uma única vez recebendo por parâmetro o próprio itensDisponiveis.contains("".."") correspondente ao botão).

Replicação de código nos métodos que retornam o caminho da imagem de cada ambiente.
* O diretório em si poderia estar em um único lugar; 
* e as subclasses de ambientes terem apenas o nome do arquivo.

Replicação de código nas diversas sobrescritas de 'pegarItemAmbiente' nas subclasses de Ambiente.

**Comment by vssjunior** [comment]
Muito obrigado pelas observaçóes professor, todos os problemas elencados acima foram resolvidos. Inclusive nos deparamos com muitos deles ao desenvolver as histórias 9 e 10.
