### ISSUE TITLE
Problemas de modelagem (e diagrama de classes)

### ISSUE THREAD

**Issue by caburu** [lucasdanielian/TrabalhoUm#43]
- [x] No diagrama as subclasses de Ambiente não têm relacionamento com as demais classes, mas no código têm.

- [x] Falta relacionamento da classe Diario (existente no código).

- [x] Relacionamento ColecaoDeItens/Item no código não é de composição.

- [x] No código a classe Item tem mais relacionamentos do que os mostrados no diagrama.

- [x] Nome das sublasses de Ambiente estão diferentes no código e no diagrama.

**Comment by vssjunior** [comment]
Todos os problemas acima foram solucionados.
