### ISSUE TITLE
Falhas não corrigidas do código original

### ISSUE THREAD

**Issue by caburu** [lucasdanielian/TrabalhoUm#45]
Nem todas as falhas existentes no código fornecido (e que são relatadas nos slides da aula de Design de Classes) foram retiradas. Exemplos:
* Continua existindo acomplamento implícito em Jogo.imprimirAjuda.
* Ajuste de saídas em Ambiente ainda recebe quantidade fixa de ambientes.

**Comment by vssjunior** [comment]
Podem ser inseridos quantos ambientes quiser, pois é um HasMap
public void ajustarSaidas( Ambiente ambiente)  {
        saidas.put(ambiente.getNomeAmbiente(), ambiente);
    }

**Comment by vssjunior** [comment]
Acabamos de corrigir o Imprimir ajuda, agora as palavras de comando são acrescentadas ao imprimir ajuda automaticamente.
