### ISSUE TITLE
Logica de Jogo nas classe ambientes em Mensagem de entrada

### ISSUE THREAD

**Issue by vssjunior** [lucasdanielian/TrabalhoUm#56]
lerPaginasDiario().equals na mensagem de entrada das classes ambientes.

**Comment by vssjunior** [comment]
Nao entendemos a observacao, se possivel gostariamos de uma explicacao um pouco mais clara de qual o problema, e se possivel uma sugestao para solucao.

**Comment by caburu** [comment]
@vssjunior não entendi; essa Issue foi aberta por você mesmo.

**Comment by vssjunior** [comment]
Vacilo aqui Júlio desculpas, essa issue foi aberta para não esquecermos de arruma aquele metodo, já foi resolvida!
