### ISSUE TITLE
Entrega 2.1 - Feedback Execução

### ISSUE THREAD

**Issue by caburu** [lucasdanielian/TrabalhoUm#79]
- comandos 'ler diario', 'analisar mochila' e 'analisar armario' no iníco do jogo parecem não fazer nada.
- comando 'ir' quando uso ambientes que não existem deveria dar mensagem diferente.
- a questão de poder tentar acessar qualquer ambiente a partir do local atual (ou pelo menos tentar) fere um pouco a ideia de um jogo adventure baseado em movimentação.
- Caixa de descrição do ambiente às vezes fica ilegível (muito pequena). Este problema me impediu de realmente conseguir jogar o jogo.
- Estando em CasaBob o botão 'Carta' foi habilitado e, ao clicar nele, coletei a carta. Mas não consigo pegar a carta via linha de comando (aparece que só é possível pegar itens em Winchester).

**Comment by vssjunior** [comment]
Alguns problemas já foram corrigidos, pois a versao baixada era a versao beta da 2.2, e nao a final da 2.1 como demonstrado em sala de aula, outros ainda precisam de mais atencao e estao na fila de prioridades de acordo com o tempo da entrega do trabalho.

**Comment by caburu** [comment]
Verificada a execução na versão correta, ficam valendo os seguintes itens:
- comandos 'ler diario', 'analisar mochila' e 'analisar armario' no iníco do jogo parecem não fazer nada.
- comando 'ir' quando uso ambientes que não existem deveria dar mensagem diferente.
- a questão de poder tentar acessar qualquer ambiente a partir do local atual (ou pelo menos tentar) fere um pouco a ideia de um jogo adventure baseado em movimentação.

**Comment by lucasdanielian** [comment]
- Comandos  "ler diario", "analisar mochila" e "analisar armario" no inicio do jogo agora possuem feedback.

- Comando "ir" quando usado em ambientes que não existem agora possui feedback personalizado.
