### ISSUE TITLE
Entrega 2.1: Diagrama de Classes

### ISSUE THREAD

**Issue by caburu** [lucasdanielian/TrabalhoUm#80]
- Diagrama UML envidao é praticamente ilegível.
- Obs: para as classes de Interface Gráfica vocês podem colocar apenas o nome da classe e mostrar os relacionamentos (sem detalhar atributos e métodos).

**Comment by vssjunior** [comment]
Realizamos as alteracoes mensionados, e como sugerido retiramos os atributos e metodos das classe referentes a interface grafica, porem o projeto ainda é muito grande, e nenhuma versao gratuita para geracao de UML nos permitiu construilo com mais clareza, pois há limitacoes quanto a numero de objetos inseridos, exportacao, uso e etc. Quaisquer sugestoes de melhoras estamos abertos a recebelas.

**Comment by caburu** [comment]
Qual foi a limitação com o software 'Dia' usado nas aulas?

Aproveitando, vi a nova versão do arquivo e segue um feedback 'adiantado' para a próxima entrega (obs: não influenciam avaliação da entrega 2.1).
- Diagrama possui classes desatualizadas (ex: Jogo x RegraDeNegocio)
- Há classes com 'Atribute1' e coisas do tipo
- Há classes de tela sem relacionamento.
- Faltam relacionamentos entre classes (ex: subclasses de Ambiente).
