### ISSUE TITLE
Entrega 2.1: Acoplamento implícito

### ISSUE THREAD

**Issue by caburu** [lucasdanielian/TrabalhoUm#82]
Issue #45 foi fechada mas acoplamento implícito ainda continua acontecendo em ImprimirAjuda.

**Comment by vssjunior** [comment]
Nao conseguimos identificar o acoplamento implicito no imprimirAjuda. Se possivel gostariamos de uma breve esplicacao para que possamos corrigir o problema.

**Comment by caburu** [comment]
Releiam os slides 31 a 36 do arquivo 'GCC178 - Parte 05 - Design de Classes.pdf'.

**Comment by vssjunior** [comment]
Acabamos de corrigir o Imprimir ajuda, agora as palavras de comando são acrescentadas ao imprimir ajuda automaticamente.
