### ISSUE TITLE
Entrega 2.1: Replicação de Código

### ISSUE THREAD

**Issue by caburu** [lucasdanielian/TrabalhoUm#83]
- Grande replicação de código nos diversos métodos prepararComponenteEstadoInicial.
- Replicação também nos tratamentos dos cliques dos botões.

**Comment by vssjunior** [comment]
- Grande replicação de código nos diversos métodos prepararComponenteEstadoInicial já foi resolvido, era apenas teste da versao beta 2.2
Replicação também nos tratamentos dos cliques dos botões, nos estamos verificando as melhores solucoes devido ao tempo de entrega da versao final 2.2.

**Comment by vssjunior** [comment]
Ambos problemas foram resolvidos.
