### ISSUE TITLE
Entrega 2.1: Modelagem

### ISSUE THREAD

**Issue by caburu** [lucasdanielian/TrabalhoUm#84]
- Porque o método 'pegarItem' existe em Ambiente se apenas uma subclasse realmente tem esse comportamento? Além disso, apesar do nome ele parece sempre pegar a Carta.
- Há um problema grave de modelagem em como os itens estão sendo usados. Estão sendo retornadas strings como 'coletado' para indicar resultado. Deveria retornar booleano ou o próprio item (dependendo do caso).
- Criadas várias subclasses de itens apenas para definir tipo. Faz sentido?

**Comment by vssjunior** [comment]
- O método 'pegarItem' é utilizado pelas classes: Houston, Denver, Ceu e CasaBob.

- Com relacao ao problema de modelagem estamos verificando a melhor solução tendo em vista a data da entrega.

- Acreditamos que as subclasses de itens fazem sim sentidos, umas que elas possuem metodos que a super classe nao tem, como getPaginas do diario pro exemplo.

**Comment by caburu** [comment]
Verificada a versão correta da entrega, nenhum dos itens listados anteriormente acontece. Mas acontece o item abaixo:
- Várias subclasses de Ambiente têm um método para retornar o item. Tal método deveria estar na superclasse e ser sobrescrito onde fosse necessário.

De qualquer forma, sobre os itens relatados anteriormente:
- Quanto ao método 'pegarItem', existe replicação de código nas subclasses. Se o item pertencesse à superclasse ambiente (e fosse a princípio, null), poderia existir apenas um método na superclasse ambiente.
- Sobre as subclasses de 'Item', só a classe 'Diario' faz sentido. As demais não acrescentam nada e poderia ser simplesmente instâncias diferentes da classe item.

**Comment by vssjunior** [comment]
Ambos os problemas foram resolvidos, obrigado pela observaçao.
