### ISSUE TITLE
Observações para Entrega 2.2

### ISSUE THREAD

**Issue by caburu** [lucasdanielian/TrabalhoUm#85]
- ter os botões de todos os itens (mesmo que desabilitados) tira um pouco da surpresa do jogo.
- botões de itens ainda não estão totalmente funcionais (ex: ao pegar a Carta no armário ela vai pra Mochila, como posso ver usando 'analisar mochila'; mas o botão do item na Mochila continua desabilitado; quando entro em um ambiente e ganho um item, o botão também não fica habilitado).

**Comment by vssjunior** [comment]
Ambos os problemas já foram corrigidos, pois a versao baixada era a versao beta da 2.2, e nao a final da 2.1 como demonstrado em sala de aula.
